version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test4"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1am0d1kuqo0so"
s3_prefix = "test4"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
